### ISSUE TITLE
Email Link doesn't work

### ISSUE THREAD

**Issue by tddostu** [Arthie/My-Personal-Website#6]
Hi, I was poking around your site (Xwind user here, thank you by the way). Your email link appears to be broken, it links to "https://arthurpetrie.com/contact@arthurpetrie.com", when clicked is shows 'error'.

Cheers,
T

**Comment by Arthie** [comment]
Hey T, interesting find!
Can you share what browser and OS you are using? I can't seem to replicate it on my machine / browsers.

Thanks for reporting this issue and using xwind!
I've just [updated my site to xwind 0.8](https://github.com/Arthie/My-Personal-Website/commit/88d1906cac420da4acabe2a60678f7debe48cfc0) and it now uses the new next.js plugin.

**Comment by tddostu** [comment]
Hi!
Chrome 88.0.4324.96, macOS 10.15.7
It also happens on Firefox 86.0b3 

It appears to be only happening on the link at bottom of the page, the one at the top seems ok.

![Screen Shot 2021-01-31 at 3 43 17 pm](https://user-images.githubusercontent.com/36751136/106375849-80832c80-63db-11eb-8f42-b42a07de7b1c.png)  
Chrome
![Screen Shot 2021-01-31 at 3 43 24 pm](https://user-images.githubusercontent.com/36751136/106375848-7f51ff80-63db-11eb-9ed6-c6acab03838a.png). 
Chrome


![Screen Shot 2021-01-31 at 3 45 32 pm](https://user-images.githubusercontent.com/36751136/106375846-7d883c00-63db-11eb-8761-d48553fb71a4.png). 
Firefox.

**Comment by Arthie** [comment]
Hey T, the link at the bottom was indeed broken and is now fixed! 

Thank you!
